hyperparameters:
  n_estimators: 100
  max_depth: 10
  random_state: 42

paths:
  data_path: "data/vgsales.csv"
  mlflow_tracking_uri: "http://localhost:8080"
  experiment_name: "video_game_sales_prediction"